"""initial platform schema

Revision ID: a29e9fc6a65d
Revises:
Create Date: 2026-08-09 06:28:42.999471
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a29e9fc6a65d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allergens",
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("name_en", sa.String(length=100), nullable=False),
        sa.Column("name_ko", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "explore_videos",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("provider_video_id", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("creator", sa.String(length=160), nullable=False),
        sa.Column("thumbnail_url", sa.Text(), nullable=True),
        sa.Column("categories", sa.JSON(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_video_id"),
    )
    op.create_table(
        "ingredients",
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("name_en", sa.String(length=100), nullable=False),
        sa.Column("name_ko", sa.String(length=100), nullable=True),
        sa.Column("emoji", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("home_country_code", sa.String(length=2), nullable=True),
        sa.Column("locale", sa.String(length=35), nullable=False),
        sa.Column("is_guest", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("roles", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_is_guest"), ["is_guest"], unique=False)

    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=60), nullable=False),
        sa.Column("resource_id", sa.String(length=100), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_action"), ["action"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_events_actor_user_id"), ["actor_user_id"], unique=False
        )
        batch_op.create_index("ix_audit_resource", ["resource_type", "resource_id"], unique=False)

    op.create_table(
        "food_passports",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("diet_codes", sa.JSON(), nullable=False),
        sa.Column("avoid_allergen_codes", sa.JSON(), nullable=False),
        sa.Column("avoid_ingredient_codes", sa.JSON(), nullable=False),
        sa.Column("liked_ingredient_codes", sa.JSON(), nullable=False),
        sa.Column("spice_tolerance", sa.Integer(), nullable=False),
        sa.Column("avoidance_details", sa.JSON(), nullable=False),
        sa.Column("disliked_textures", sa.JSON(), nullable=False),
        sa.Column("learned_preferences", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "media_assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_user_id", sa.String(length=36), nullable=False),
        sa.Column("purpose", sa.String(length=40), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    with op.batch_alter_table("media_assets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_media_assets_owner_user_id"), ["owner_user_id"], unique=False
        )

    op.create_table(
        "restaurants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("owner_user_id", sa.String(length=36), nullable=True),
        sa.Column("name_en", sa.String(length=160), nullable=False),
        sa.Column("name_ko", sa.String(length=160), nullable=True),
        sa.Column("description_en", sa.Text(), nullable=False),
        sa.Column("description_ko", sa.Text(), nullable=True),
        sa.Column("handle", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("hero_style", sa.String(length=30), nullable=False),
        sa.Column("address_en", sa.String(length=300), nullable=False),
        sa.Column("address_ko", sa.String(length=300), nullable=True),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("timezone_name", sa.String(length=50), nullable=False),
        sa.Column("rating_avg", sa.Numeric(precision=2, scale=1), nullable=False),
        sa.Column("rating_count", sa.Integer(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("menu_revision", sa.Integer(), nullable=False),
        sa.Column("cover_image_url", sa.Text(), nullable=True),
        sa.Column("gallery", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("handle"),
    )
    with op.batch_alter_table("restaurants", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_restaurants_is_published"), ["is_published"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_restaurants_latitude"), ["latitude"], unique=False)
        batch_op.create_index(batch_op.f("ix_restaurants_longitude"), ["longitude"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_restaurants_owner_user_id"), ["owner_user_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_restaurants_slug"), ["slug"], unique=True)

    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=64), nullable=False),
        sa.Column("client_type", sa.String(length=20), nullable=False),
        sa.Column("device_id", sa.String(length=255), nullable=True),
        sa.Column("scope", sa.String(length=40), nullable=False),
        sa.Column("qr_restaurant_id", sa.String(length=36), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["qr_restaurant_id"], ["restaurants.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_auth_sessions_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_auth_sessions_refresh_token_hash"), ["refresh_token_hash"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_auth_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "carts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("restaurant_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("serving_mode", sa.String(length=30), nullable=False),
        sa.Column("table_label", sa.String(length=50), nullable=True),
        sa.Column("menu_revision", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["restaurant_id"], ["restaurants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("carts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_carts_restaurant_id"), ["restaurant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_carts_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_carts_user_status", ["user_id", "status"], unique=False)

    op.create_table(
        "conversations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("restaurant_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=160), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["restaurant_id"], ["restaurants.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversations_restaurant_id"), ["restaurant_id"], unique=False
        )

    op.create_table(
        "menu_categories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("restaurant_id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name_en", sa.String(length=100), nullable=False),
        sa.Column("name_ko", sa.String(length=100), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["restaurant_id"], ["restaurants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("restaurant_id", "slug"),
    )
    with op.batch_alter_table("menu_categories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_menu_categories_restaurant_id"), ["restaurant_id"], unique=False
        )

    op.create_table(
        "opening_hours",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("restaurant_id", sa.String(length=36), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("opens_at", sa.Time(), nullable=True),
        sa.Column("closes_at", sa.Time(), nullable=True),
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.CheckConstraint("day_of_week >= 0 AND day_of_week <= 6", name="ck_opening_hour_day"),
        sa.ForeignKeyConstraint(["restaurant_id"], ["restaurants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("restaurant_id", "day_of_week"),
    )
    with op.batch_alter_table("opening_hours", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_opening_hours_restaurant_id"), ["restaurant_id"], unique=False
        )

    op.create_table(
        "orders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("restaurant_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("serving_mode", sa.String(length=30), nullable=False),
        sa.Column("subtotal_amount", sa.Integer(), nullable=False),
        sa.Column("total_amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("korean_phrase", sa.Text(), nullable=False),
        sa.Column("translated_phrase", sa.Text(), nullable=False),
        sa.Column("allergy_note_ko", sa.Text(), nullable=True),
        sa.Column("allergy_note_localized", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["restaurant_id"], ["restaurants.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "idempotency_key"),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_orders_restaurant_id"), ["restaurant_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_orders_user_id"), ["user_id"], unique=False)

    op.create_table(
        "owner_applications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("applicant_user_id", sa.String(length=36), nullable=False),
        sa.Column("restaurant_id", sa.String(length=36), nullable=True),
        sa.Column("business_name", sa.String(length=200), nullable=False),
        sa.Column("registration_number", sa.String(length=30), nullable=False),
        sa.Column("address", sa.String(length=300), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column("license_media_id", sa.String(length=36), nullable=False),
        sa.Column("agreed_to_terms_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("terms_version", sa.String(length=30), nullable=False),
        sa.Column("phone_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["applicant_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["license_media_id"], ["media_assets.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["restaurant_id"], ["restaurants.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("owner_applications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_owner_applications_applicant_user_id"),
            ["applicant_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_owner_applications_registration_number"),
            ["registration_number"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_owner_applications_restaurant_id"), ["restaurant_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_owner_applications_status"), ["status"], unique=False)

    op.create_table(
        "qr_codes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("public_hint", sa.String(length=12), nullable=False),
        sa.Column("restaurant_id", sa.String(length=36), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.Column("table_label", sa.String(length=50), nullable=True),
        sa.Column("purpose", sa.String(length=30), nullable=False),
        sa.Column("menu_revision", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["restaurant_id"], ["restaurants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("qr_codes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_qr_codes_code_hash"), ["code_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_qr_codes_is_active"), ["is_active"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_qr_codes_restaurant_id"), ["restaurant_id"], unique=False
        )

    op.create_table(
        "restaurant_memberships",
        sa.Column("restaurant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["restaurant_id"], ["restaurants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("restaurant_id", "user_id"),
    )
    op.create_table(
        "restaurant_translations",
        sa.Column("restaurant_id", sa.String(length=36), nullable=False),
        sa.Column("locale", sa.String(length=35), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("address", sa.String(length=300), nullable=False),
        sa.ForeignKeyConstraint(["restaurant_id"], ["restaurants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("restaurant_id", "locale"),
    )
    op.create_table(
        "saved_restaurants",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("restaurant_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["restaurant_id"], ["restaurants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "restaurant_id"),
    )
    op.create_table(
        "conversation_participants",
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("last_read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("conversation_id", "user_id"),
    )
    op.create_table(
        "menu_category_translations",
        sa.Column("category_id", sa.String(length=36), nullable=False),
        sa.Column("locale", sa.String(length=35), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["menu_categories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("category_id", "locale"),
    )
    op.create_table(
        "menu_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("restaurant_id", sa.String(length=36), nullable=False),
        sa.Column("category_id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name_en", sa.String(length=160), nullable=False),
        sa.Column("name_ko", sa.String(length=160), nullable=True),
        sa.Column("pronunciation", sa.String(length=200), nullable=True),
        sa.Column("description_en", sa.Text(), nullable=False),
        sa.Column("description_ko", sa.Text(), nullable=True),
        sa.Column("price_amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("serving_description", sa.String(length=200), nullable=True),
        sa.Column("spice_level", sa.Integer(), nullable=False),
        sa.Column("taste_profile", sa.JSON(), nullable=False),
        sa.Column("local_tips", sa.JSON(), nullable=False),
        sa.Column("badge", sa.String(length=40), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("media", sa.JSON(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("price_amount >= 0", name="ck_menu_item_price_nonnegative"),
        sa.CheckConstraint("spice_level >= 0 AND spice_level <= 5", name="ck_menu_item_spice"),
        sa.ForeignKeyConstraint(["category_id"], ["menu_categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["restaurant_id"], ["restaurants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("restaurant_id", "slug"),
    )
    with op.batch_alter_table("menu_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_menu_items_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(
            "ix_menu_items_restaurant_available", ["restaurant_id", "is_available"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_menu_items_restaurant_id"), ["restaurant_id"], unique=False
        )

    op.create_table(
        "messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("sender_user_id", sa.String(length=36), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("client_message_id", sa.String(length=100), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("media_asset_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["media_asset_id"], ["media_assets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["sender_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "conversation_id", "sender_user_id", "client_message_id", name="uq_message_client_id"
        ),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_messages_conversation_created", ["conversation_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_messages_conversation_id"), ["conversation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_messages_sender_user_id"), ["sender_user_id"], unique=False
        )

    op.create_table(
        "qr_scans",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("qr_code_id", sa.String(length=36), nullable=False),
        sa.Column("scanned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locale", sa.String(length=35), nullable=True),
        sa.Column("client_type", sa.String(length=20), nullable=False),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(["qr_code_id"], ["qr_codes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("qr_scans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_qr_scans_qr_code_id"), ["qr_code_id"], unique=False)

    op.create_table(
        "cart_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("cart_id", sa.String(length=36), nullable=False),
        sa.Column("menu_item_id", sa.String(length=36), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price_snapshot", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("request_codes", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("quantity > 0", name="ck_cart_item_quantity_positive"),
        sa.CheckConstraint("unit_price_snapshot >= 0", name="ck_cart_item_price_nonnegative"),
        sa.ForeignKeyConstraint(["cart_id"], ["carts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["menu_item_id"], ["menu_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cart_id", "menu_item_id"),
    )
    with op.batch_alter_table("cart_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cart_items_cart_id"), ["cart_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_cart_items_menu_item_id"), ["menu_item_id"], unique=False
        )

    op.create_table(
        "menu_item_allergens",
        sa.Column("menu_item_id", sa.String(length=36), nullable=False),
        sa.Column("allergen_code", sa.String(length=60), nullable=False),
        sa.Column("relation_type", sa.String(length=30), nullable=False),
        sa.Column("verification_status", sa.String(length=30), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["allergen_code"], ["allergens.code"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["menu_item_id"], ["menu_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("menu_item_id", "allergen_code", "relation_type"),
    )
    op.create_table(
        "menu_item_dietary_claims",
        sa.Column("menu_item_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("verification_status", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(["menu_item_id"], ["menu_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("menu_item_id", "code"),
    )
    op.create_table(
        "menu_item_ingredients",
        sa.Column("menu_item_id", sa.String(length=36), nullable=False),
        sa.Column("ingredient_code", sa.String(length=60), nullable=False),
        sa.Column("detail_en", sa.String(length=300), nullable=True),
        sa.Column("detail_ko", sa.String(length=300), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["ingredient_code"], ["ingredients.code"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["menu_item_id"], ["menu_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("menu_item_id", "ingredient_code"),
    )
    op.create_table(
        "menu_item_translations",
        sa.Column("menu_item_id", sa.String(length=36), nullable=False),
        sa.Column("locale", sa.String(length=35), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("pronunciation", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(["menu_item_id"], ["menu_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("menu_item_id", "locale"),
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("order_id", sa.String(length=36), nullable=False),
        sa.Column("menu_item_id", sa.String(length=36), nullable=True),
        sa.Column("name_en_snapshot", sa.String(length=160), nullable=False),
        sa.Column("name_ko_snapshot", sa.String(length=160), nullable=False),
        sa.Column("unit_price_amount", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(["menu_item_id"], ["menu_items.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_order_items_order_id"), ["order_id"], unique=False)

    op.create_table(
        "reviews",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("menu_item_id", sa.String(length=36), nullable=False),
        sa.Column("author_user_id", sa.String(length=36), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("author_display_name", sa.String(length=100), nullable=False),
        sa.Column("author_country_code", sa.String(length=2), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("rating >= 1 AND rating <= 5", name="ck_review_rating"),
        sa.ForeignKeyConstraint(["author_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["menu_item_id"], ["menu_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reviews_author_user_id"), ["author_user_id"], unique=False
        )
        batch_op.create_index(
            "ix_reviews_item_created", ["menu_item_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_reviews_menu_item_id"), ["menu_item_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reviews_menu_item_id"))
        batch_op.drop_index("ix_reviews_item_created")
        batch_op.drop_index(batch_op.f("ix_reviews_author_user_id"))

    op.drop_table("reviews")
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_items_order_id"))

    op.drop_table("order_items")
    op.drop_table("menu_item_translations")
    op.drop_table("menu_item_ingredients")
    op.drop_table("menu_item_dietary_claims")
    op.drop_table("menu_item_allergens")
    with op.batch_alter_table("cart_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cart_items_menu_item_id"))
        batch_op.drop_index(batch_op.f("ix_cart_items_cart_id"))

    op.drop_table("cart_items")
    with op.batch_alter_table("qr_scans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_qr_scans_qr_code_id"))

    op.drop_table("qr_scans")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_sender_user_id"))
        batch_op.drop_index(batch_op.f("ix_messages_conversation_id"))
        batch_op.drop_index("ix_messages_conversation_created")

    op.drop_table("messages")
    with op.batch_alter_table("menu_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_menu_items_restaurant_id"))
        batch_op.drop_index("ix_menu_items_restaurant_available")
        batch_op.drop_index(batch_op.f("ix_menu_items_category_id"))

    op.drop_table("menu_items")
    op.drop_table("menu_category_translations")
    op.drop_table("conversation_participants")
    op.drop_table("saved_restaurants")
    op.drop_table("restaurant_translations")
    op.drop_table("restaurant_memberships")
    with op.batch_alter_table("qr_codes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_qr_codes_restaurant_id"))
        batch_op.drop_index(batch_op.f("ix_qr_codes_is_active"))
        batch_op.drop_index(batch_op.f("ix_qr_codes_code_hash"))

    op.drop_table("qr_codes")
    with op.batch_alter_table("owner_applications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_owner_applications_status"))
        batch_op.drop_index(batch_op.f("ix_owner_applications_restaurant_id"))
        batch_op.drop_index(batch_op.f("ix_owner_applications_registration_number"))
        batch_op.drop_index(batch_op.f("ix_owner_applications_applicant_user_id"))

    op.drop_table("owner_applications")
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_orders_user_id"))
        batch_op.drop_index(batch_op.f("ix_orders_restaurant_id"))

    op.drop_table("orders")
    with op.batch_alter_table("opening_hours", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_opening_hours_restaurant_id"))

    op.drop_table("opening_hours")
    with op.batch_alter_table("menu_categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_menu_categories_restaurant_id"))

    op.drop_table("menu_categories")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_restaurant_id"))

    op.drop_table("conversations")
    with op.batch_alter_table("carts", schema=None) as batch_op:
        batch_op.drop_index("ix_carts_user_status")
        batch_op.drop_index(batch_op.f("ix_carts_user_id"))
        batch_op.drop_index(batch_op.f("ix_carts_restaurant_id"))

    op.drop_table("carts")
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_auth_sessions_refresh_token_hash"))
        batch_op.drop_index(batch_op.f("ix_auth_sessions_expires_at"))

    op.drop_table("auth_sessions")
    with op.batch_alter_table("restaurants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_restaurants_slug"))
        batch_op.drop_index(batch_op.f("ix_restaurants_owner_user_id"))
        batch_op.drop_index(batch_op.f("ix_restaurants_longitude"))
        batch_op.drop_index(batch_op.f("ix_restaurants_latitude"))
        batch_op.drop_index(batch_op.f("ix_restaurants_is_published"))

    op.drop_table("restaurants")
    with op.batch_alter_table("media_assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_media_assets_owner_user_id"))

    op.drop_table("media_assets")
    op.drop_table("food_passports")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_resource")
        batch_op.drop_index(batch_op.f("ix_audit_events_actor_user_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_action"))

    op.drop_table("audit_events")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_is_guest"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    op.drop_table("ingredients")
    op.drop_table("explore_videos")
    op.drop_table("allergens")
    # ### end Alembic commands ###
